version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: harbor-postgres-prod
    restart: unless-stopped
    networks:
      - harbor-network
    environment:
      POSTGRES_DB: ${DB_NAME:-harbor_prod}
      POSTGRES_USER: ${DB_USER:-harbor_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    command: ["postgres", "-c", "ssl=off"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-harbor_user} -d ${DB_NAME:-harbor_prod}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true

  # Backend API Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: production
      args:
        - NODE_ENV=production
    container_name: harbor-backend-prod
    restart: unless-stopped
    networks:
      - harbor-network
      - nginx-proxy-manager_npm_network
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT:-3001}
      NODE_OPTIONS: "--openssl-legacy-provider"

      # Database configuration
      DB_HOST: ${DB_HOST:-harbor-postgres-prod}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-harbor_prod}
      DB_USER: ${DB_USER:-harbor_user}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL: false

      # JWT configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-1h}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}

      # Frontend URL for CORS
      FRONTEND_URL: https://harbor.roboetech.com
      CORS_ORIGIN: ${CORS_ORIGIN:-http://harbor.roboetech.com,https://harbor.roboetech.com}

      # Production flags - Mock settings removed

      # LDAP configuration
      LDAP_URL: ${LDAP_URL}
      LDAP_BIND_DN: ${LDAP_BIND_DN}
      LDAP_BIND_CREDENTIALS: ${LDAP_BIND_CREDENTIALS}
      LDAP_SEARCH_BASE: ${LDAP_SEARCH_BASE}
      LDAP_SEARCH_FILTER: ${LDAP_SEARCH_FILTER}
      LDAP_TIMEOUT: ${LDAP_TIMEOUT}
      LDAP_CONNECT_TIMEOUT: ${LDAP_CONNECT_TIMEOUT}
      LDAP_RECONNECT: ${LDAP_RECONNECT}
      LDAP_IDLE_TIMEOUT: ${LDAP_IDLE_TIMEOUT}
      LDAP_ATTR_USERNAME: ${LDAP_ATTR_USERNAME}
      LDAP_ATTR_EMAIL: ${LDAP_ATTR_EMAIL}
      LDAP_ATTR_FULL_NAME: ${LDAP_ATTR_FULL_NAME}
      LDAP_ATTR_DEPARTMENT: ${LDAP_ATTR_DEPARTMENT}
      LDAP_DEFAULT_EMAIL_DOMAIN: ${LDAP_DEFAULT_EMAIL_DOMAIN}
      LDAP_DN_TEMPLATE: ${LDAP_DN_TEMPLATE}
      LDAP_DEFAULT_DEPARTMENT_FALLBACK: ${LDAP_DEFAULT_DEPARTMENT_FALLBACK}
      LDAP_DEFAULT_DEPARTMENT: ${LDAP_DEFAULT_DEPARTMENT}
      LDAP_GROUP_BASE: ${LDAP_GROUP_BASE}
      LDAP_PORT: ${LDAP_PORT}

      # Jenkins Configuration
      JENKINS_URL: ${JENKINS_URL}
      JENKINS_USERNAME: ${JENKINS_USERNAME}
      JENKINS_PASSWORD: ${JENKINS_PASSWORD}
      JENKINS_WEBHOOK_SECRET: ${JENKINS_WEBHOOK_SECRET}
      
      # Rate Limiting - DISABLED
      RATE_LIMIT_LOGIN: 999999
      MAX_LOGIN_ATTEMPTS: 999999
      LOCKOUT_DURATION: 1
      DISABLE_RATE_LIMITING: true

      # Synology NAS API configuration
      SYNOLOGY_BASE_URL: ${SYNOLOGY_BASE_URL}
      SYNOLOGY_USERNAME: ${SYNOLOGY_USERNAME}
      SYNOLOGY_PASSWORD: ${SYNOLOGY_PASSWORD}
      SYNOLOGY_SESSION_NAME: ${SYNOLOGY_SESSION_NAME}
      SYNOLOGY_DEVICE_NAME: ${SYNOLOGY_DEVICE_NAME:-Harbor-Backend}
      SYNOLOGY_DEVICE_ID: ${SYNOLOGY_DEVICE_ID:-harbor-backend-001}
      SYNOLOGY_FORMAT: ${SYNOLOGY_FORMAT:-sid}
      
      # NAS configuration
      NAS_RELEASE_PATH: ${NAS_RELEASE_PATH:-release_version}
      NAS_SCAN_INTERVAL: ${NAS_SCAN_INTERVAL:-*/15 * * * *}
      NAS_MAX_FILE_SIZE: ${NAS_MAX_FILE_SIZE:-2147483648}
      NAS_ALLOWED_EXTENSIONS: ${NAS_ALLOWED_EXTENSIONS:-.tar.gz,.zip,.jar,.war,.tgz}
      NAS_WATCH_ENABLED: ${NAS_WATCH_ENABLED:-true}
      NAS_SCHEDULER_ENABLED: ${NAS_SCHEDULER_ENABLED:-true}

      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-info}
    volumes:
      - ./backend/src:/app/src
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs

  # Frontend Web Server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: production
      args:
        - VITE_API_URL=/api
        - VITE_WS_URL=wss://harbor.roboetech.com
    container_name: harbor-frontend-prod
    restart: unless-stopped
    networks:
      - harbor-network
      - nginx-proxy-manager_npm_network
    ports:
      - "8080:8080"
    environment:
      NGINX_WORKER_PROCESSES: auto
      NGINX_WORKER_CONNECTIONS: 1024
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    security_opt:
      - no-new-privileges:true



networks:
  harbor-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  nginx-proxy-manager_npm_network:
    external: true

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local
