version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: harbor-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-harbor_prod}
      POSTGRES_USER: ${DB_USER:-harbor_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - harbor-network
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-harbor_user} -d ${DB_NAME:-harbor_prod}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true

  # OpenLDAP (Optional - for development/testing)
  openldap:
    image: osixia/openldap:1.5.0
    container_name: harbor-openldap-prod
    restart: unless-stopped
    environment:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION:-Harbor Organization}
      LDAP_DOMAIN: ${LDAP_DOMAIN:-harbor.local}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD}
      LDAP_READONLY_USER: true
      LDAP_READONLY_USER_USERNAME: ${LDAP_READONLY_USER:-readonly}
      LDAP_READONLY_USER_PASSWORD: ${LDAP_READONLY_PASSWORD}
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - harbor-network
    ports:
      - "${LDAP_PORT:-389}:389"
      - "${LDAPS_PORT:-636}:636"
    profiles:
      - ldap
    security_opt:
      - no-new-privileges:true

  # Backend API Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: production
      args:
        - NODE_ENV=production
    container_name: harbor-backend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3002

      # Database configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-harbor_prod}
      DB_USER: ${DB_USER:-harbor_user}
      DB_PASSWORD: ${DB_PASSWORD}

      # JWT configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-1h}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}

      # LDAP configuration
      LDAP_URL: ${LDAP_URL:-ldap://openldap:389}
      LDAP_BIND_DN: ${LDAP_BIND_DN}
      LDAP_BIND_CREDENTIALS: ${LDAP_BIND_CREDENTIALS}
      LDAP_SEARCH_BASE: ${LDAP_SEARCH_BASE}

      # Jenkins Webhook
      JENKINS_WEBHOOK_SECRET: ${JENKINS_WEBHOOK_SECRET}

      # NAS configuration
      NAS_PATH: ${NAS_PATH:-/nas}

      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-info}
    volumes:
      - app_logs:/app/logs
      - nas_data:/nas:ro
    networks:
      - harbor-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs

  # Frontend Web Server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: production
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3002}
    container_name: harbor-frontend-prod
    restart: unless-stopped
    environment:
      NGINX_WORKER_PROCESSES: auto
      NGINX_WORKER_CONNECTIONS: 1024
    networks:
      - harbor-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run

  # Reverse Proxy & Load Balancer
  nginx:
    image: nginx:1.25-alpine
    container_name: harbor-nginx-prod
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - harbor-network
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    security_opt:
      - no-new-privileges:true

  # Redis for Session Storage and Caching
  redis:
    image: redis:7-alpine
    container_name: harbor-redis-prod
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - harbor-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    security_opt:
      - no-new-privileges:true

networks:
  harbor-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
    driver: local
  ldap_data:
    driver: local
  ldap_config:
    driver: local
  redis_data:
    driver: local
  app_logs:
    driver: local
  nginx_logs:
    driver: local
  nas_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${NAS_HOST_PATH:-./nas-mock}